services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask_todo_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=todo_user
      - MONGO_PASSWORD=passer
      - MONGO_DB=todo_db
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - todo_network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=todo_user
      - MONGO_INITDB_ROOT_PASSWORD=passer
      - MONGO_INITDB_DATABASE=todo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - todo_network
    restart: unless-stopped

networks:
  todo_network:
    driver: bridge

volumes:
  mongodb_data: