name: Status Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Jenkins Status
        uses: actions/github-script@v6
        with:
          script: |
            const { data: statuses } = await github.rest.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            
            const jenkinsStatus = statuses.statuses.find(
              status => status.context === 'CI/CD Pipeline'
            );
            
            if (!jenkinsStatus) {
              core.setFailed('Jenkins status check not found');
              return;
            }
            
            if (jenkinsStatus.state !== 'success') {
              core.setFailed(`Jenkins build failed: ${jenkinsStatus.description}`);
            }